// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OverwatchAPI.Data.Context;

namespace OverwatchAPI.Data.Migrations
{
    [DbContext(typeof(OverwatchContext))]
    partial class OverwatchContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OverwatchAPI.Domain.DomainClasses.Dashboard.Dashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("ProjectId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Dashboards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "dit is een disc",
                            Name = "First",
                            ProjectId = 1
                        });
                });

            modelBuilder.Entity("OverwatchAPI.Domain.DomainClasses.Projects.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Overwatch",
                            Url = "an url"
                        });
                });

            modelBuilder.Entity("OverwatchAPI.Domain.DomainClasses.Widgets.Widget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color");

                    b.Property<int>("DashboardId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.ToTable("Widgets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red1",
                            DashboardId = 1,
                            Name = "Demo11"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Red2",
                            DashboardId = 1,
                            Name = "Demo12"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Red3",
                            DashboardId = 1,
                            Name = "Demo13"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Red4",
                            DashboardId = 1,
                            Name = "Demo14"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Red5",
                            DashboardId = 1,
                            Name = "Demo15"
                        });
                });

            modelBuilder.Entity("OverwatchAPI.Domain.DomainClasses.Dashboard.Dashboard", b =>
                {
                    b.HasOne("OverwatchAPI.Domain.DomainClasses.Projects.Project", "Project")
                        .WithMany("Dashboards")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OverwatchAPI.Domain.DomainClasses.Widgets.Widget", b =>
                {
                    b.HasOne("OverwatchAPI.Domain.DomainClasses.Dashboard.Dashboard", "Dashboard")
                        .WithMany("Widgets")
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
