// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OverwatchAPI.Data.Context;

namespace OverwatchAPI.Data.Migrations
{
    [DbContext(typeof(OverwatchContext))]
    partial class OverwatchContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OverwatchAPI.Domain.DomainClasses.Dashboard.Dashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("ProjectId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("OverwatchAPI.Domain.DomainClasses.Projects.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("OverwatchAPI.Domain.DomainClasses.Widgets.Widget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color");

                    b.Property<int?>("DashboardId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.ToTable("Widget");
                });

            modelBuilder.Entity("OverwatchAPI.Domain.DomainClasses.Dashboard.Dashboard", b =>
                {
                    b.HasOne("OverwatchAPI.Domain.DomainClasses.Projects.Project")
                        .WithMany("Dashboards")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("OverwatchAPI.Domain.DomainClasses.Widgets.Widget", b =>
                {
                    b.HasOne("OverwatchAPI.Domain.DomainClasses.Dashboard.Dashboard")
                        .WithMany("Widgets")
                        .HasForeignKey("DashboardId");
                });
#pragma warning restore 612, 618
        }
    }
}
